resources:
  - ./deployment-bnbusdt-1m.yaml
  - ./deployment-bnbusdt-1h.yaml
  - ./deployment-bnbusdt-4h.yaml
commonLabels:
  app.kubernetes.io/component: backend
  app.kubernetes.io/name: strategy
  app.kubernetes.io/version: "1.0"